local M = {}

function M.get(c, _opts)
	return {
		TroubleNormal            = { fg = c.fg_dim, bg = c.bg_terminal },
		TroubleNormalNC          = { fg = c.fg_dim, bg = c.bg_terminal },
		TroubleText              = { fg = c.fg_dim },
		TroubleSource            = { fg = c.fg_mute, italic = true },
		TroubleCode              = { fg = c.fg_mute },
		TroubleCount             = { fg = c.func, bold = true },
		TroubleFoldIcon          = { fg = c.fg_mute },
		TroubleIndent            = { fg = "#8384854d" },
		TroubleIndentFoldClosed  = { fg = c.fg_mute },
		TroubleIndentTop         = { fg = "#8384854d" },
		TroubleIndentMiddle      = { fg = "#8384854d" },
		TroubleIndentLast        = { fg = "#8384854d" },
		TroubleLocation          = { fg = c.fg_mute },
		TroubleFile              = { fg = c.fg_bright, bold = true },
		TroubleDirectory         = { fg = c.constant },
		TroublePos               = { fg = c.fg_mute },
		TroublePreview           = { bg = c.accent .. "26" },
		TroubleBasename          = { fg = c.fg_dim },
		TroubleIconArray         = { fg = c.markup_list },
		TroubleIconBoolean       = { fg = c.boolean },
		TroubleIconClass         = { fg = c.type },
		TroubleIconConstant      = { fg = c.constant },
		TroubleIconConstructor   = { fg = c.func },
		TroubleIconEnum          = { fg = c.type },
		TroubleIconEnumMember    = { fg = c.constant },
		TroubleIconEvent         = { fg = c.variable },
		TroubleIconField         = { fg = c.variable },
		TroubleIconFile          = { fg = c.fg_dim },
		TroubleIconFunction      = { fg = c.func },
		TroubleIconInterface     = { fg = c.type },
		TroubleIconKey           = { fg = c.keyword },
		TroubleIconMethod        = { fg = c.func },
		TroubleIconModule        = { fg = c.type },
		TroubleIconNamespace     = { fg = c.type },
		TroubleIconNull          = { fg = c.boolean },
		TroubleIconNumber        = { fg = c.number },
		TroubleIconObject        = { fg = c.func },
		TroubleIconOperator      = { fg = c.operator },
		TroubleIconPackage       = { fg = c.type },
		TroubleIconProperty      = { fg = c.variable },
		TroubleIconString        = { fg = c.string },
		TroubleIconStruct        = { fg = c.type },
		TroubleIconTypeParameter = { fg = c.type },
		TroubleIconVariable      = { fg = c.variable },
	}
end

return M
